language: node_js
# nodejs版本
node_js: 
    - '6'

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - katex
env:
 global:
   # 我将其添加到了travis-ci的环境变量中
   #- GH_REF: github.com/yimogit/metools.git 

after_success:
- npm run deploy-storybook -- --ci --host-token-env-variable=GH_TOKEN